config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {:registrations => "registrations"}

  devise_scope :user do
    authenticated :user do
      root 'items#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :items
  resources :user do
    resources :orders
  end

  resources :order do
    resources :order_items
  end
  resources :waiters

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items, dependent: :destroy

  validate :delivery_time_cannot_be_earlier_than_present

  def delivery_time_cannot_be_earlier_than_present
    if delivery_time.present?
    	input_time = delivery_time.change(:min => 0)
  		current_time = (DateTime.now).change(:min => 0)
  		if input_time < current_time
      	errors.add(:delivery_time, "can't be earlier than the present time")
    	end
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	load_and_authorize_resource :user
	load_and_authorize_resource :order

	def index 								#GET    /user/:user_id/orders
		if @user.waiter?
			@orders = @user.orders
			respond_to do |format|
	    	format.html
	  	end
	  else
	  	respond_to do |format|
	    	format.html
	  	end
		end
	end

	def create 								#POST   /user/:user_id/orders
		if current_user.admin?
			@order.user = current_user
		end
		if @order.save
			#binding.pry
			respond_to do |format|
	    	format.html { redirect_to user_order_path(@user, @order), notice: 'Order successfully created.' }
	  	end
		else
			flash.now[:alert] = "Order could not be created."
			respond_to do |format|
	    	format.html { render 'new' }
	  	end
		end
	end

	def update 								#PUT    /user/:user_id/orders/:id
		if @order.update(order_params)
			respond_to do |format|
	    	format.html { redirect_to user_order_path(@user, @order), notice: 'Order successfully updated.' }
	    end
		else
			flash.now[:alert] = 'Order could not be updated.'
			respond_to do |format|
	    	format.html { render 'edit' }
	    end
		end
	end

	def destroy								#DELETE /user/:user_id/orders/:id
		if @order.destroy
			flash[:notice] = "Order deleted."
		else
			flash[:alert] = "Order could not be deleted."
		end
		respond_to do |format|
	    	format.html { redirect_to user_orders_path(@user) }
	  end
	end

	private
	def order_params
		params.require(:order).permit(:status, :description, :delivery_time)
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-lg-2">
  </div>
  <div class="col-lg-8">

  <%= form_for ([@user, @order]) do |f| %>

    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h3>
          <%= pluralize(@order.errors.count, "error") %> prevented this order from being saved:
        </h3>
        <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <p>
        <%= f.label :description %><br>
        <%= f.text_field :description, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :status %><br>
        <%= f.select :status, options_for_select([['Pending','Pending'],['In progress','In progress'],['Compeleted','Compeleted']]), {}, {class: 'form-control'} %>
      </p>

      <p>
        <%= f.label :delivery_time %><br>
        <%= f.datetime_select :delivery_time, :ampm => true, class: 'form-control' %>
      </p>
      <br>
      <p>
        <div class="text-center"><%= f.submit "Submit", class: 'btn btn-default'%></div>
      </p>
    </div>
  <% end %>
</div>
<div class="col-lg-2">
</div>

</div>

app/views/orders/edit.html.erb
<h2 class="text-center">Edit Order</h2>

<%= render 'form' %>

app/views/orders/index.html.erb
<h2 class="text-center">Orders</h2>

<table class="table table-striped">
  <tr>
    <th>Staff email</th>
    <th>Order Description</th>
    <th>Order Status</th>
    <th>Time of Delivery</th>
    <th colspan="4"></th>
  </tr>

  <% @orders.each do |order| %>
  <% if order.user %>
    <tr>
      <td><%= order.user.email %></td>
      <td><%= order.description %></td>
      <td><%= order.status %></td>
      <td><%= order.delivery_time %></td>
      <td> <%= link_to 'Show', user_order_path(order.user, order) %> </td>
      <% if can? :manage, Order %>
        <td> <%= link_to 'Display Order Items', order_order_items_path(order) %> </td>
        <td> <%= link_to 'Edit', edit_user_order_path(order.user, order) %> </td>
        <td> <%= link_to 'Delete', [order.user, order],
                 method: :delete,
                 data: {confirm: 'Are you sure you want to delete this order?' } %> </td>
      <% end %>
    </tr>
    <% end %>
  <% end %>
</table>

<% if can? :manage, Order %>
  <div class="text-center"><%= link_to 'New order', new_user_order_path, class: 'btn btn-default'%></div>
<% end %>

app/views/orders/new.html.erb
<h2 class="text-center">Add New Order</h2>

<%= render 'form' %>

app/views/orders/show.html.erb
<div class="row">
  <div class="col-lg-2">
  </div>
  <div class="col-lg-8">
  	<br>
		<table class="table table-striped table-bordered">
			<tr>
				<td><strong>Order Description: </strong></td>
				<td><%= @order.description %></td>
			</tr>
			<tr>
				<td><strong>Order Status: </strong></td>
				<td><%= @order.status %></td>
			</tr>
			<tr>
				<td><strong>Order Delivery Time:</strong> </td>
				<td><%= @order.delivery_time %></td>
			</tr>
		</table>
	</div>
	<div class="col-lg-2">
  </div>
</div>