config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {:registrations => "registrations"}

  devise_scope :user do
    authenticated :user do
      root 'items#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :items
  resources :user do
    resources :orders
  end

  resources :order do
    resources :order_items
  end
  resources :waiters

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :quantity, :numericality => { :greater_than_or_equal_to => 0 }
	validates :price, :numericality => { :greater_than => 0 }
	validates_presence_of :name

	has_many :order_items, dependent: :destroy
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	load_and_authorize_resource

	def create 								#POST /items/:id
		if @item.save
			respond_to do |format|
    		format.html { redirect_to @item, notice: 'Item successfully added.' }
 			end
		else
			flash.now[:alert] = 'Item could not be created.'
			respond_to do |format|
    		format.html { render 'new' }
			end
		end
	end

	def update 								#PUT /items/:id
		if @item.update(item_params)
			respond_to do |format|
				format.html { redirect_to @item, notice: 'Item successfully updated.' }
			end
		else
			flash.now[:alert] = 'Item could not be updated.'
			respond_to do |format|
    		format.html { render 'edit' }
    	end
		end
	end

	def destroy 							#DELETE /items/:id
		if @item.destroy
			flash[:notice] = 'Item successfully deleted'
		else
			flash[:alert] = 'Item could not be deleted'
		end
		respond_to do |format|
    		format.html { redirect_to items_path }
    end
	end

	private
	def item_params
		params.require(:item).permit(:name, :quantity, :price)
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="row">
  <div class="col-lg-2">
  </div>
  <div class="col-lg-8">

  <%= form_for @item do |f| %>
    <% if @item.errors.any? %>
      <div id="error_explanation">
        <h3>
          <%= pluralize(@item.errors.count, "error") %> prevented this item from being saved:
        </h3>
        <ul>
          <% @item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control', required: true %>
      </p>

      <p>
        <%= f.label :quantity %><br>
        <%= f.number_field :quantity, class: 'form-control', input_html: { min: '0'} %>
      </p>

      <p>
        <%= f.label :price %><br>
        <%= f.number_field :price, class: 'form-control', input_html: { min: '0'} %>
      </p>

      <p>
        <div class="text-center"><%= f.submit "Submit", class: 'btn btn-default' %></div>
      </p>

    </div>
  <% end %>

  </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/items/edit.html.erb
<h2 class="text-center">Edit Item</h2>

<%= render 'form' %>

app/views/items/index.html.erb
<h2 class="text-center">Menu</h2>

<table class="table table-striped">
  <tr>
    <th>Item Name</th>
    <th>Quantity</th>
    <th>Price</th>
    <th colspan="3"></th>
  </tr>

  <% @items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.quantity %></td>
      <td><%= item.price %></td>
      <td><%= link_to 'Show', item_path(item) %></td>
      <% if can? :manage, Item %>
      <td><%= link_to 'Edit', edit_item_path(item) %></td>
      <td><%= link_to 'Delete', item_path(item),
               method: :delete,
               data: {confirm: 'Are you sure you want to delete this item?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<% if can? :manage, Item %>
<div class="text-center"><%= link_to 'New item', new_item_path, class: 'btn btn-default' %></div>
<% end %>

app/views/items/new.html.erb
<h2 class="text-center">Add New Item</h2>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="row">
  <div class="col-lg-2">
  </div>
  <div class="col-lg-8">
  	<br>
		<table class="table table-striped table-bordered">
			<tr>
				<td><strong>Item Name: </strong></td>
				<td><%= @item.name %></td>
			</tr>
			<tr>
				<td><strong>Quantity in Stock: </strong></td>
				<td><%= @item.quantity %></td>
			</tr>
			<tr>
				<td><strong>Price:</strong> </td>
				<td><%= @item.price %></td>
			</tr>
		</table>
	</div>
	<div class="col-lg-2">
  </div>

</div>