config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {:registrations => "registrations"}

  devise_scope :user do
    authenticated :user do
      root 'items#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :items
  resources :user do
    resources :orders
  end

  resources :order do
    resources :order_items
  end
  resources :waiters

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order

  validates :quantity, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
	load_and_authorize_resource :order
	load_and_authorize_resource :order_item, through: :order

	def new 									#GET    /order/:order_id/order_items/new
		@items = Item.all
		respond_to do |format|
  		format.js
  		format.html
		end
	end

	def edit 									#GET    /order/:order_id/order_items/:id/edit
		@items = Item.all
		respond_to do |format|
  		format.html
		end
	end

	def create 								#POST   /order/:order_id/order_items
		@items = Item.all
		if @order_item.item.quantity >= @order_item.quantity
			if @order_item.save
				@order_item.item.update(quantity: (@order_item.item.quantity - @order_item.quantity))
				flash[:notice] = 'Order item successfully added.'
				respond_to do |format|
					format.js
  				format.html { redirect_to [@order, @order_item] }
				end
			else
				flash[:alert] = "Order item could not be added beacuse of #{@order_item.errors.full_messages}."
				respond_to do |format|
					format.js
  				format.html { render 'new' }
				end
			end
		else
			flash[:alert] = 'Order item quantity cannot be greater than item stock quantity.'
			respond_to do |format|
					format.js
  				format.html { render 'new' }
				end
		end
	end

	def update 								#PUT    /order/:order_id/order_items/:id
		@items = Item.all
		if check_updated_quantity
			if @order_item.update(order_item_params)
				respond_to do |format|
  				format.html { redirect_to [@order, @order_item], notice: 'Order item successfully updated.' }
				end
			else
				flash.now[:alert] = 'Order item could not be updated.'
				respond_to do |format|
  				format.html { render 'edit' }
				end
			end
		else
			flash[:alert] = 'Order items could not be updated, not enough items in stock.'
			respond_to do |format|
  				format.html { render 'edit' }
			end
		end
	end

	def destroy								#DELETE /order/:order_id/order_items/:id
		if @order_item.destroy
			flash[:notice] = 'Order item successfully deleted.'
		else
			flash[:alert] = 'Order item could not be deleted.'
		end
		respond_to do |format|
  		format.html { redirect_to order_order_items_path(@order) }
		end
	end

	private
	def order_item_params
		params.require(:order_item).permit(:item_id, :quantity)
	end

	def check_updated_quantity
		if (params[:order_item][:quantity]).to_i > @order_item.quantity
			quantity_diff  = params[:order_item][:quantity].to_i - @order_item.quantity
			@order_item.item.update(quantity: @order_item.item.quantity - quantity_diff)
		else
			quantity_diff  = @order_item.quantity - params[:order_item][:quantity].to_i
			@order_item.item.update(quantity: @order_item.item.quantity + quantity_diff)
		end
	end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title text-center" id="myModalLabel">Add New Order Item</h4>
    </div>
    <div class="modal-body">
      <div class="container">
      <%= form_for [@order, @order_item], remote: true do |f| %>

        <% if @order_item.errors.any? %>
          <div id="error_explanation">
           <h3><%= pluralize(@order_item.errors.count, "error") %> prevented this order item from being saved:</h3>
            <ul>
              <% @order_item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <p>
          <%= f.label :item_id %><br>
          <%= f.collection_select :item_id, @items, :id, :name %>
        </p>

        <p>
          <%= f.label :quantity %><br>
          <%= f.number_field :quantity, input_html: { min: '0'} %>
        </p>

        <p>
          <%= f.submit %>
        </p>
        <% end %>

      </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
    </div>
  </div>
</div>

app/views/order_items/create.js.erb
window.location.reload();

app/views/order_items/edit.html.erb
<div class="row">
  <div class="col-lg-2">
  </div>
  <div class="col-lg-8">

  <h2 class="text-center">Edit Order Item</h2>


  <%= form_for [@order, @order_item] do |f| %>

    <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prevented this order item from being saved:</h2>
        <ul>
        <% @order_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
    <div class="form-group">
      <p>
        <%= f.label :item_id %><br>
        <%= f.collection_select :item_id, @items, :id, :name, {}, { class: 'form-control' } %>
      </p>

      <p>
        <%= f.label :quantity %><br>
        <%= f.number_field :quantity, class: 'form-control' %>
      </p>

      <p>
        <div class="text-center"><%= f.submit "Edit Order Item", class: 'btn btn-default' %></div>
      </p>
      <% end %>
    </div>

  </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/order_items/index.html.erb
<h2 class="text-center">Order Items</h2>

<table id="order_items" class="table table-striped">
  <tr>
    <th colspan="5" class="text-center">Order ID: <%= @order.id %></th>
  </tr>
  <tr>
    <th colspan="5" class="text-center">Order Description: <%= @order.description %></th>
  </tr>
  <tr>
    <th colspan="5" class="text-center">Order Status: <%= @order.status %></th>
  </tr>
  <tr>
    <th>Item Name</th>
    <th>Quantity</th>
    <th colspan="3"></th>
  </tr>

  <% @order_items.each do |order_item| %>
    <tr>
      <td><%= order_item.item.name %></td>
      <td><%= order_item.quantity %></td>
      <td><%= link_to 'Show', order_order_item_path(order_item.order, order_item) %></td>
      <% if can? :manage, Order %>
        <td><%= link_to 'Edit', edit_order_order_item_path(order_item.order, order_item) %></td>
        <td><%= link_to 'Delete', [order_item.order, order_item],
                 method: :delete,
                 data: { confirm: 'Are you sure you want to delete this item?' } %></td>
        <% end %>
    </tr>
  <% end %>
</table>

<div class="modal fade" id="modal_form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<% if can? :manage, Order %>
  <div class="text-center"><%= link_to 'New item', new_order_order_item_path, remote: true, class: 'btn btn-default' %></div>
<% end %>

app/views/order_items/new.html.erb
<h2>Add New Order Item</h2>

<%= render 'form' %>

app/views/order_items/new.js.erb
$("#modal_form").html("<%= escape_javascript (render 'form') %>");
$("#modal_form").modal('show');

app/views/order_items/show.html.erb
<div class="row">
  <div class="col-lg-2">
  </div>
  <div class="col-lg-8">
  	<br>
		<table class="table table-striped table-bordered">
			<tr>
				<td><strong>Item Name: </strong></td>
				<td><%= @order_item.item.name %></td>
			</tr>
			<tr>
				<td><strong>Quantity: </strong></td>
				<td><%= @order_item.quantity %></td>
			</tr>
		</table>
	</div>
	<div class="col-lg-2">
  </div>
</div>