config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {:registrations => "registrations"}

  devise_scope :user do
    authenticated :user do
      root 'items#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :items
  resources :user do
    resources :orders
  end

  resources :order do
    resources :order_items
  end
  resources :waiters

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant Management System</title>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
</head>
<body>


<% if user_signed_in? %>
<div class="pull-right">
  <%= current_user.name %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-default' %>
</div>
<div class="btn-group">
		<%= link_to 'Items', items_path, class: 'btn btn-default' %>
		<%= link_to 'Orders', user_orders_path(current_user), class: 'btn btn-default' %>
  <% if current_user.admin? %>
  	<%= link_to 'Waiters', waiters_path, class: 'btn btn-default' %>
  <% end %>
<% else %>
  <%= link_to 'Login', new_user_session_path, class: 'btn btn-default' %>
<% end %>
</div>
<br>
<div class="container">
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</div>
</body>
</html>